services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - web
      - api
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: /api
    depends_on:
      - api
    networks:
      - appnet

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./env.prod
    environment:
      NODE_ENV: production
      RECS_URL: http://localhost:5000
    depends_on:
      - postgres
      - mongo
      - recs
    networks:
      - appnet

  recs:
    build:
      context: ..
      dockerfile: apps/recs/Dockerfile
    networks:
      - appnet

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./env.prod
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
      POSTGRES_DB: shop_ubuntu
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    networks:
      - appnet
      
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - ./env.prod
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
        redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"
      else
        redis-server --appendonly yes
      fi'
    volumes:
      - redisdata:/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
  mongodata:
  redisdata:

networks:
  appnet:
    driver: bridge
